:bitbucket-v2 = https://api.bitbucket.org/2.0
:username := (emacs-bitbucket--test-data-username (emacs-bitbucket--get-test-data))
:repo-slug := (emacs-bitbucket--test-data-repo-slug (emacs-bitbucket--get-test-data))
:pull-request-id := (emacs-bitbucket--test-data-pull-request-id (emacs-bitbucket--get-test-data))
:commit-hash := (emacs-bitbucket--test-data-commit-hash (emacs-bitbucket--get-test-data))
:destination-commit-hash := (emacs-bitbucket--test-data-destination-commit-hash (emacs-bitbucket--get-test-data))
:token := (oauth2-token-access-token (oauth2-extension--get-token))

# /repositories/{username}
GET :bitbucket-v2/repositories/:username?pagelen=30
Authorization: Bearer :token

# POST /repositories/{username}/{repo_slug}/pullrequests/{pull_request_id}/approve
POST :bitbucket-v2/repositories/:username/:repo-slug/pullrequests/:pull-request-id/approve
Authorization: Bearer :token

# DELETE /repositories/{username}/{repo_slug}/pullrequests/{pull_request_id}/approve
DELETE :bitbucket-v2/repositories/:username/:repo-slug/pullrequests/:pull-request-id/approve
Authorization: Bearer :token

# GET /repositories/{username}/{repo_slug}
GET :bitbucket-v2/repositories/:username/:repo-slug
Authorization: Bearer :token

# GET /repositories/{username}/{repo_slug}/commits
GET :bitbucket-v2/repositories/:username/:repo-slug/commits
Authorization: Bearer :token

# GET /repositories/{username}/{repo_slug}/refs/branches
GET :bitbucket-v2/repositories/:username/:repo-slug/refs/branches?pagelen=30
Authorization: Bearer :token

# GET /repositories/{username}/{repo_slug}/diff/{spec}
GET :bitbucket-v2/repositories/:username/:repo-slug/diff/:commit-hash
Authorization: Bearer :token

# You may add the -L option in the cURL command to get the result
# GET /repositories/{username}/{repo_slug}/pullrequests/{pull_request_id}/diff
GET :bitbucket-v2/repositories/:username/:repo-slug/pullrequests/:pull-request-id/diff
Authorization: Bearer :token
Content-Type: text/plain

# Pull request diff redirected url
# /:username/:repo-slug/diff/:username/:repo-slug:07db936de9e8%0D8a0a91a7cdcc
GET :bitbucket-v2/repositories/:username/:repo-slug/diff/:destination-commit-hash
Authorization: Bearer :token
Content-Type: text/plain

# GET /repositories/mgmdevptm/testrepo/pullrequests
GET :bitbucket-v2/repositories/:username/:repo-slug/pullrequests
Authorization: Bearer :token

# POST /repositories/mgmdevptm/testrepo/pullrequests
POST :bitbucket-v2/repositories/:username/:repo-slug/pullrequests
Authorization: Bearer :token
Content-Type: application/json

{
  "source":
  {
    "branch":
    {
      "name": "branch1"
    }
  },
  "destination":
  {
    "branch":
    {
      "name": "master"
    }
  },
  "reviewers": [
    {
      "uuid": "{c24a8446-194c-40f9-90bd-0146a3a306a6}"
    }
  ],
  "title": "Dummy pullrequest"
}

# GET /2.0/teams/{username}/members
GET :bitbucket-v2/teams/:username/members
Authorization: Bearer :token