;; output of /<user>/repositories/

((pagelen . 10)
 (size . 41)
 (values .
         [((scm . git)
           (website . )
           (has_wiki . :json-false)
           (name . teste1)
           (links
            (watchers (href . https://api.bitbucket.org/2.0/repositories/mmoritz/teste1/watchers))
            (branches (href . https://api.bitbucket.org/2.0/repositories/mmoritz/teste1/refs/branches))
            (tags (href . https://api.bitbucket.org/2.0/repositories/mmoritz/teste1/refs/tags))
            (commits (href . https://api.bitbucket.org/2.0/repositories/mmoritz/teste1/commits))
            (clone . [((href . https://mmoritz@bitbucket.org/mmoritz/teste1.git) (name . https))
                      ((href . git@bitbucket.org:mmoritz/teste1.git) (name . ssh))])
            (self (href . https://api.bitbucket.org/2.0/repositories/mmoritz/teste1))
            (source (href . https://api.bitbucket.org/2.0/repositories/mmoritz/teste1/src))
            (html (href . https://bitbucket.org/mmoritz/teste1))
            (avatar (href . https://bitbucket.org/mmoritz/teste1/avatar/32/))
            (hooks (href . https://api.bitbucket.org/2.0/repositories/mmoritz/teste1/hooks))
            (forks (href . https://api.bitbucket.org/2.0/repositories/mmoritz/teste1/forks))
            (downloads (href . https://api.bitbucket.org/2.0/repositories/mmoritz/teste1/downloads))
            (issues (href . https://api.bitbucket.org/2.0/repositories/mmoritz/teste1/issues))
            (pullrequests (href . https://api.bitbucket.org/2.0/repositories/mmoritz/teste1/pullrequests)))
           (fork_policy . no_public_forks)
           (uuid . {8b6bbb49-10fd-41b7-a88b-730e8922d791})
           (language . c#)
           (created_on . 2013-09-27T16:30:17.673429+00:00)
           (mainbranch (type . branch) (name . master))
           (full_name . mmoritz/teste1)
           (has_issues . t)
           (owner (username . mmoritz)
                  (display_name . Marcos Moritz)
                  (type . user)
                  (uuid . {f5165058-864e-43f4-aece-609d7bca7e78})
                  (links (self (href . https://api.bitbucket.org/2.0/users/mmoritz))
                         (html (href . https://bitbucket.org/mmoritz/))
                         (avatar (href . https://bitbucket.org/account/mmoritz/avatar/32/))))
           (updated_on . 2013-09-27T22:08:23.389794+00:00)
           (size . 84357)
           (type . repository)
           (slug . teste1)
           (is_private . t)
           (description . repositÃ³rio online de teste))

          ((scm . git)
           (website .)
           (has_wiki . :json-false)
           (name . Flute Friend)
           (links (watchers (href . https://api.bitbucket.org/2.0/repositories/mmoritz/flute-friend/watchers))
                  (branches (href . https://api.bitbucket.org/2.0/repositories/mmoritz/flute-friend/refs/branches))
                  (tags (href . https://api.bitbucket.org/2.0/repositories/mmoritz/flute-friend/refs/tags))
                  (commits (href . https://api.bitbucket.org/2.0/repositories/mmoritz/flute-friend/commits))
                  (clone . [((href . https://mmoritz@bitbucket.org/mmoritz/flute-friend.git) (name . https))
                            ((href . git@bitbucket.org:mmoritz/flute-friend.git) (name . ssh))])
                  (self (href . https://api.bitbucket.org/2.0/repositories/mmoritz/flute-friend))
                  (source (href . https://api.bitbucket.org/2.0/repositories/mmoritz/flute-friend/src))
                  (html (href . https://bitbucket.org/mmoritz/flute-friend))
                  (avatar (href . https://bitbucket.org/mmoritz/flute-friend/avatar/32/))
                  (hooks (href . https://api.bitbucket.org/2.0/repositories/mmoritz/flute-friend/hooks))
                  (forks (href . https://api.bitbucket.org/2.0/repositories/mmoritz/flute-friend/forks))
                  (downloads (href . https://api.bitbucket.org/2.0/repositories/mmoritz/flute-friend/downloads))
                  (pullrequests (href . https://api.bitbucket.org/2.0/repositories/mmoritz/flute-friend/pullrequests)))
           (fork_policy . no_public_forks)
           (uuid . {5da9f969-325b-429b-b8c5-465b3eae3eeb})
           (language . processing)
           (created_on . 2014-04-10T18:29:37.104030+00:00)
           (mainbranch (type . branch) (name . master))
           (full_name . mmoritz/flute-friend)
           (has_issues . :json-false)
           (owner (username . mmoritz)
                  (display_name . Marcos Moritz)
                  (type . user)
                  (uuid . {f5165058-864e-43f4-aece-609d7bca7e78})
                  (links (self (href . https://api.bitbucket.org/2.0/users/mmoritz))
                         (html (href . https://bitbucket.org/mmoritz/))
                         (avatar (href . https://bitbucket.org/account/mmoritz/avatar/32/))))
           (updated_on . 2014-11-06T18:31:13.118954+00:00)
           (size . 4555996)
           (type . repository)
           (slug . flute-friend)
           (is_private . t)
           (description . Support for teaching/leaning to play the flute.))
          ((scm . git)
           (website .)
           (has_wiki . :json-false)
           (name . CameraSonifier)
           (links (watchers (href . https://api.bitbucket.org/2.0/repositories/mmoritz/camerasonifier/watchers))
                  (branches (href . https://api.bitbucket.org/2.0/repositories/mmoritz/camerasonifier/refs/branches))
                  (tags (href . https://api.bitbucket.org/2.0/repositories/mmoritz/camerasonifier/refs/tags))
                  (commits (href . https://api.bitbucket.org/2.0/repositories/mmoritz/camerasonifier/commits))
                  (clone . [((href . https://mmoritz@bitbucket.org/mmoritz/camerasonifier.git) (name . https))
                            ((href . git@bitbucket.org:mmoritz/camerasonifier.git) (name . ssh))])
                  (self (href . https://api.bitbucket.org/2.0/repositories/mmoritz/camerasonifier))
                  (source (href . https://api.bitbucket.org/2.0/repositories/mmoritz/camerasonifier/src))
                  (html (href . https://bitbucket.org/mmoritz/camerasonifier))
                  (avatar (href . https://bitbucket.org/mmoritz/camerasonifier/avatar/32/))
                  (hooks (href . https://api.bitbucket.org/2.0/repositories/mmoritz/camerasonifier/hooks))
                  (forks (href . https://api.bitbucket.org/2.0/repositories/mmoritz/camerasonifier/forks))
                  (downloads (href . https://api.bitbucket.org/2.0/repositories/mmoritz/camerasonifier/downloads))
                  (pullrequests (href . https://api.bitbucket.org/2.0/repositories/mmoritz/camerasonifier/pullrequests)))
           (fork_policy . no_public_forks)
           (uuid . {1f8fdaeb-2e25-4577-ad2d-7f6342b7833a})
           (language . c++)
           (created_on . 2014-05-02T16:54:08.881783+00:00)
           (mainbranch (type . branch) (name . master))
           (full_name . mmoritz/camerasonifier)
           (has_issues . :json-false)
           (owner (username . mmoritz)
                  (display_name . Marcos Moritz)
                  (type . user)
                  (uuid . {f5165058-864e-43f4-aece-609d7bca7e78})
                  (links (self (href . https://api.bitbucket.org/2.0/users/mmoritz))
                         (html (href . https://bitbucket.org/mmoritz/))
                         (avatar (href . https://bitbucket.org/account/mmoritz/avatar/32/))))
           (updated_on . 2014-12-07T06:48:01.609172+00:00)
           (size . 164914)
           (type . repository)
           (slug . camerasonifier)
           (is_private . t)
           (description . Show a bunch of reactions to movement detected by a regular camera.))
          ((scm . git)
           (website .)
           (has_wiki . :json-false)
           (name . Drawer)
           (links (watchers (href . https://api.bitbucket.org/2.0/repositories/mmoritz/drawer/watchers))
                  (branches (href . https://api.bitbucket.org/2.0/repositories/mmoritz/drawer/refs/branches))
                  (tags (href . https://api.bitbucket.org/2.0/repositories/mmoritz/drawer/refs/tags))
                  (commits (href . https://api.bitbucket.org/2.0/repositories/mmoritz/drawer/commits))
                  (clone . [((href . https://mmoritz@bitbucket.org/mmoritz/drawer.git) (name . https))
                            ((href . git@bitbucket.org:mmoritz/drawer.git) (name . ssh))])
                  (self (href . https://api.bitbucket.org/2.0/repositories/mmoritz/drawer))
                  (source (href . https://api.bitbucket.org/2.0/repositories/mmoritz/drawer/src))
                  (html (href . https://bitbucket.org/mmoritz/drawer))
                  (avatar (href . https://bitbucket.org/mmoritz/drawer/avatar/32/))
                  (hooks (href . https://api.bitbucket.org/2.0/repositories/mmoritz/drawer/hooks))
                  (forks (href . https://api.bitbucket.org/2.0/repositories/mmoritz/drawer/forks))
                  (downloads (href . https://api.bitbucket.org/2.0/repositories/mmoritz/drawer/downloads))
                  (pullrequests (href . https://api.bitbucket.org/2.0/repositories/mmoritz/drawer/pullrequests)))
           (fork_policy . no_public_forks)
           (uuid . {791591e2-f87e-4409-8d29-eebde71235e3})
           (language . java)
           (created_on . 2014-05-20T14:57:01.812073+00:00)
           (mainbranch (type . branch) (name . master))
           (full_name . mmoritz/drawer)
           (has_issues . :json-false)
           (owner (username . mmoritz)
                  (display_name . Marcos Moritz)
                  (type . user)
                  (uuid . {f5165058-864e-43f4-aece-609d7bca7e78})
                  (links (self (href . https://api.bitbucket.org/2.0/users/mmoritz))
                         (html (href . https://bitbucket.org/mmoritz/))
                         (avatar (href . https://bitbucket.org/account/mmoritz/avatar/32/))))
           (updated_on . 2015-05-22T20:35:16.676333+00:00)
           (size . 1201707)
           (type . repository)
           (slug . drawer)
           (is_private . t)
           (description . Drawing app))
          ((scm . git)
           (website .)
           (has_wiki . :json-false)
           (name . KinectTest)
           (links (watchers (href . https://api.bitbucket.org/2.0/repositories/mmoritz/kinecttest/watchers))
                  (branches (href . https://api.bitbucket.org/2.0/repositories/mmoritz/kinecttest/refs/branches))
                  (tags (href . https://api.bitbucket.org/2.0/repositories/mmoritz/kinecttest/refs/tags))
                  (commits (href . https://api.bitbucket.org/2.0/repositories/mmoritz/kinecttest/commits))
                  (clone . [((href . https://mmoritz@bitbucket.org/mmoritz/kinecttest.git) (name . https))
                            ((href . git@bitbucket.org:mmoritz/kinecttest.git) (name . ssh))])
                  (self (href . https://api.bitbucket.org/2.0/repositories/mmoritz/kinecttest))
                  (source (href . https://api.bitbucket.org/2.0/repositories/mmoritz/kinecttest/src))
                  (html (href . https://bitbucket.org/mmoritz/kinecttest))
                  (avatar (href . https://bitbucket.org/mmoritz/kinecttest/avatar/32/))
                  (hooks (href . https://api.bitbucket.org/2.0/repositories/mmoritz/kinecttest/hooks))
                  (forks (href . https://api.bitbucket.org/2.0/repositories/mmoritz/kinecttest/forks))
                  (downloads (href . https://api.bitbucket.org/2.0/repositories/mmoritz/kinecttest/downloads))
                  (pullrequests (href . https://api.bitbucket.org/2.0/repositories/mmoritz/kinecttest/pullrequests)))
           (fork_policy . no_public_forks)
           (uuid . {cfb89391-4fe5-4e48-9ef4-9f421046845e})
           (language . unityscript)
           (created_on . 2014-06-01T09:29:10.938143+00:00)
           (mainbranch (type . branch) (name . master))
           (full_name . mmoritz/kinecttest)
           (has_issues . :json-false)
           (owner (username . mmoritz)
                  (display_name . Marcos Moritz)
                  (type . user)
                  (uuid . {f5165058-864e-43f4-aece-609d7bca7e78})
                  (links (self (href . https://api.bitbucket.org/2.0/users/mmoritz))
                         (html (href . https://bitbucket.org/mmoritz/))
                         (avatar (href . https://bitbucket.org/account/mmoritz/avatar/32/))))
           (updated_on . 2014-09-23T17:39:43.860766+00:00)
           (size . 27968088)
           (type . repository)
           (slug . kinecttest)
           (is_private . t)
           (description . Test for soccer game using Kinect))
          ((scm . git)
           (website .)
           (has_wiki . :json-false)
           (name . DrawFlashcards)
           (links (watchers (href . https://api.bitbucket.org/2.0/repositories/mmoritz/drawflashcards/watchers))
                  (branches (href . https://api.bitbucket.org/2.0/repositories/mmoritz/drawflashcards/refs/branches))
                  (tags (href . https://api.bitbucket.org/2.0/repositories/mmoritz/drawflashcards/refs/tags))
                  (commits (href . https://api.bitbucket.org/2.0/repositories/mmoritz/drawflashcards/commits))
                  (clone . [((href . https://mmoritz@bitbucket.org/mmoritz/drawflashcards.git) (name . https))
                            ((href . git@bitbucket.org:mmoritz/drawflashcards.git) (name . ssh))])
                  (self (href . https://api.bitbucket.org/2.0/repositories/mmoritz/drawflashcards))
                  (source (href . https://api.bitbucket.org/2.0/repositories/mmoritz/drawflashcards/src))
                  (html (href . https://bitbucket.org/mmoritz/drawflashcards))
                  (avatar (href . https://bitbucket.org/mmoritz/drawflashcards/avatar/32/))
                  (hooks (href . https://api.bitbucket.org/2.0/repositories/mmoritz/drawflashcards/hooks))
                  (forks (href . https://api.bitbucket.org/2.0/repositories/mmoritz/drawflashcards/forks))
                  (downloads (href . https://api.bitbucket.org/2.0/repositories/mmoritz/drawflashcards/downloads))
                  (pullrequests (href . https://api.bitbucket.org/2.0/repositories/mmoritz/drawflashcards/pullrequests)))
           (fork_policy . no_public_forks)
           (uuid . {c7e72150-67b6-4d9f-9d4f-621475b04fc2})
           (language . android)
           (created_on . 2014-10-23T15:59:13.818927+00:00)
           (mainbranch (type . branch) (name . master))
           (full_name . mmoritz/drawflashcards)
           (has_issues . :json-false)
           (owner (username . mmoritz)
                  (display_name . Marcos Moritz)
                  (type . user)
                  (uuid . {f5165058-864e-43f4-aece-609d7bca7e78})
                  (links (self (href . https://api.bitbucket.org/2.0/users/mmoritz))
                         (html (href . https://bitbucket.org/mmoritz/))
                         (avatar (href . https://bitbucket.org/account/mmoritz/avatar/32/))))
           (updated_on . 2015-05-25T19:08:29.923973+00:00)
           (size . 899474)
           (type . repository)
           (slug . drawflashcards)
           (is_private . t)
           (description . Draw your own flashcards to make them more significant.))
          ((scm . git)
           (website .)
           (has_wiki . :json-false)
           (name . Flauteando)
           (links (watchers (href . https://api.bitbucket.org/2.0/repositories/mmoritz/flauteando/watchers)) (branches (href . https://api.bitbucket.org/2.0/repositories/mmoritz/flauteando/refs/branches)) (tags (href . https://api.bitbucket.org/2.0/repositories/mmoritz/flauteando/refs/tags)) (commits (href . https://api.bitbucket.org/2.0/repositories/mmoritz/flauteando/commits)) (clone . [((href . https://mmoritz@bitbucket.org/mmoritz/flauteando.git) (name . https)) ((href . git@bitbucket.org:mmoritz/flauteando.git) (name . ssh))]) (self (href . https://api.bitbucket.org/2.0/repositories/mmoritz/flauteando)) (source (href . https://api.bitbucket.org/2.0/repositories/mmoritz/flauteando/src)) (html (href . https://bitbucket.org/mmoritz/flauteando)) (avatar (href . https://bitbucket.org/mmoritz/flauteando/avatar/32/)) (hooks (href . https://api.bitbucket.org/2.0/repositories/mmoritz/flauteando/hooks)) (forks (href . https://api.bitbucket.org/2.0/repositories/mmoritz/flauteando/forks)) (downloads (href . https://api.bitbucket.org/2.0/repositories/mmoritz/flauteando/downloads)) (pullrequests (href . https://api.bitbucket.org/2.0/repositories/mmoritz/flauteando/pullrequests)))
           (fork_policy . no_public_forks)
           (uuid . {ae7bda0c-6e50-4645-a828-86620a9ee7eb})
           (language . android)
           (created_on . 2014-11-14T08:44:29.692315+00:00)
           (mainbranch (type . branch) (name . master))
           (full_name . mmoritz/flauteando)
           (has_issues . :json-false)
           (owner (username . mmoritz)
                  (display_name . Marcos Moritz)
                  (type . user)
                  (uuid . {f5165058-864e-43f4-aece-609d7bca7e78})
                  (links (self (href . https://api.bitbucket.org/2.0/users/mmoritz))
                         (html (href . https://bitbucket.org/mmoritz/))
                         (avatar (href . https://bitbucket.org/account/mmoritz/avatar/32/))))
           (updated_on . 2014-12-04T04:01:29.078952+00:00)
           (size . 1844506)
           (type . repository)
           (slug . flauteando)
           (is_private . t)
           (description . Help you to learn how to play the recorder (musical instrument).))
          ((scm . git)
           (website .)
           (has_wiki . :json-false)
           (name . RaceThree)
           (links (watchers (href . https://api.bitbucket.org/2.0/repositories/mmoritz/racethree/watchers)) (branches (href . https://api.bitbucket.org/2.0/repositories/mmoritz/racethree/refs/branches)) (tags (href . https://api.bitbucket.org/2.0/repositories/mmoritz/racethree/refs/tags)) (commits (href . https://api.bitbucket.org/2.0/repositories/mmoritz/racethree/commits)) (clone . [((href . https://mmoritz@bitbucket.org/mmoritz/racethree.git) (name . https)) ((href . git@bitbucket.org:mmoritz/racethree.git) (name . ssh))]) (self (href . https://api.bitbucket.org/2.0/repositories/mmoritz/racethree)) (source (href . https://api.bitbucket.org/2.0/repositories/mmoritz/racethree/src)) (html (href . https://bitbucket.org/mmoritz/racethree)) (avatar (href . https://bitbucket.org/mmoritz/racethree/avatar/32/)) (hooks (href . https://api.bitbucket.org/2.0/repositories/mmoritz/racethree/hooks)) (forks (href . https://api.bitbucket.org/2.0/repositories/mmoritz/racethree/forks)) (downloads (href . https://api.bitbucket.org/2.0/repositories/mmoritz/racethree/downloads)) (pullrequests (href . https://api.bitbucket.org/2.0/repositories/mmoritz/racethree/pullrequests)))
           (fork_policy . no_public_forks)
           (uuid . {16def395-a04b-408a-8ab0-a17df509bceb})
           (language . c#)
           (created_on . 2014-12-04T22:03:47.275092+00:00)
           (mainbranch (type . branch) (name . master))
           (full_name . mmoritz/racethree)
           (has_issues . :json-false)
           (owner (username . mmoritz)
                  (display_name . Marcos Moritz)
                  (type . user)
                  (uuid . {f5165058-864e-43f4-aece-609d7bca7e78})
                  (links (self (href . https://api.bitbucket.org/2.0/users/mmoritz))
                         (html (href . https://bitbucket.org/mmoritz/))
                         (avatar (href . https://bitbucket.org/account/mmoritz/avatar/32/))))
           (updated_on . 2014-12-06T05:33:15.134597+00:00)
           (size . 38514140)
           (type . repository)
           (slug . racethree)
           (is_private . t)
           (description . Exploratory Racing Game))
          ((scm . git)
           (website . ) (has_wiki . :json-false)
           (name . Video Player)
           (links (watchers (href . https://api.bitbucket.org/2.0/repositories/mmoritz/video-player/watchers)) (branches (href . https://api.bitbucket.org/2.0/repositories/mmoritz/video-player/refs/branches)) (tags (href . https://api.bitbucket.org/2.0/repositories/mmoritz/video-player/refs/tags)) (commits (href . https://api.bitbucket.org/2.0/repositories/mmoritz/video-player/commits)) (clone . [((href . https://mmoritz@bitbucket.org/mmoritz/video-player.git) (name . https)) ((href . git@bitbucket.org:mmoritz/video-player.git) (name . ssh))]) (self (href . https://api.bitbucket.org/2.0/repositories/mmoritz/video-player)) (source (href . https://api.bitbucket.org/2.0/repositories/mmoritz/video-player/src)) (html (href . https://bitbucket.org/mmoritz/video-player)) (avatar (href . https://bitbucket.org/mmoritz/video-player/avatar/32/)) (hooks (href . https://api.bitbucket.org/2.0/repositories/mmoritz/video-player/hooks)) (forks (href . https://api.bitbucket.org/2.0/repositories/mmoritz/video-player/forks)) (downloads (href . https://api.bitbucket.org/2.0/repositories/mmoritz/video-player/downloads)) (pullrequests (href . https://api.bitbucket.org/2.0/repositories/mmoritz/video-player/pullrequests)))
           (fork_policy . no_public_forks)
           (uuid . {2c41641a-4fdd-43d1-b3fd-6337a11a0197})
           (language . java)
           (created_on . 2015-04-15T16:24:51.263715+00:00)
           (mainbranch (type . branch) (name . master))
           (full_name . mmoritz/video-player)
           (has_issues . :json-false)
           (owner (username . mmoritz)
                  (display_name . Marcos Moritz)
                  (type . user)
                  (uuid . {f5165058-864e-43f4-aece-609d7bca7e78})
                  (links (self (href . https://api.bitbucket.org/2.0/users/mmoritz))
                         (html (href . https://bitbucket.org/mmoritz/))
                         (avatar (href . https://bitbucket.org/account/mmoritz/avatar/32/))))
           (updated_on . 2015-04-15T17:05:49.602688+00:00)
           (size . 21811243)
           (type . repository)
           (slug . video-player)
           (is_private . t)
           (description . Create interactions with a video sample))
          ((scm . git)
           (website .)
           (has_wiki . :json-false)
           (name . Artificio Website)
           (links (watchers (href . https://api.bitbucket.org/2.0/repositories/mmoritz/artificio-website/watchers))
                  (branches (href . https://api.bitbucket.org/2.0/repositories/mmoritz/artificio-website/refs/branches))
                  (tags (href . https://api.bitbucket.org/2.0/repositories/mmoritz/artificio-website/refs/tags))
                  (commits (href . https://api.bitbucket.org/2.0/repositories/mmoritz/artificio-website/commits))
                  (clone . [((href . https://mmoritz@bitbucket.org/mmoritz/artificio-website.git) (name . https))
                            ((href . git@bitbucket.org:mmoritz/artificio-website.git) (name . ssh))])
                  (self (href . https://api.bitbucket.org/2.0/repositories/mmoritz/artificio-website))
                  (source (href . https://api.bitbucket.org/2.0/repositories/mmoritz/artificio-website/src))
                  (html (href . https://bitbucket.org/mmoritz/artificio-website))
                  (avatar (href . https://bitbucket.org/mmoritz/artificio-website/avatar/32/))
                  (hooks (href . https://api.bitbucket.org/2.0/repositories/mmoritz/artificio-website/hooks))
                  (forks (href . https://api.bitbucket.org/2.0/repositories/mmoritz/artificio-website/forks))
                  (downloads (href . https://api.bitbucket.org/2.0/repositories/mmoritz/artificio-website/downloads))
                  (pullrequests (href . https://api.bitbucket.org/2.0/repositories/mmoritz/artificio-website/pullrequests)))
           (fork_policy . no_public_forks)
           (uuid . {20d2b653-72e7-423c-9afc-918317969c7c})
           (language . ruby)
           (created_on . 2015-07-10T04:07:50.627463+00:00)
           (mainbranch (type . branch) (name . master))
           (full_name . mmoritz/artificio-website)
           (has_issues . :json-false)
           (owner (username . mmoritz)
                  (display_name . Marcos Moritz)
                  (type . user)
                  (uuid . {f5165058-864e-43f4-aece-609d7bca7e78})
                  (links (self (href . https://api.bitbucket.org/2.0/users/mmoritz))
                         (html (href . https://bitbucket.org/mmoritz/))
                         (avatar (href . https://bitbucket.org/account/mmoritz/avatar/32/))))
           (updated_on . 2015-08-17T17:04:43.848210+00:00)
           (size . 8011479)
           (type . repository)
           (slug . artificio-website)
           (is_private . t)
           (description . ArtifÃ­cio Modas Website))])
 (page . 1)
 (next . https://api.bitbucket.org/2.0/repositories/mmoritz?page=2))
