[(
  (description . )
  (links
   (decline (href . https://api.bitbucket.org/2.0/repositories/ptmtech/frontend2/pullrequests/167/decline))
   (commits (href . https://api.bitbucket.org/2.0/repositories/ptmtech/frontend2/pullrequests/167/commits))
   (self (href . https://api.bitbucket.org/2.0/repositories/ptmtech/frontend2/pullrequests/167))
   (comments (href . https://api.bitbucket.org/2.0/repositories/ptmtech/frontend2/pullrequests/167/comments))
   (merge (href . https://api.bitbucket.org/2.0/repositories/ptmtech/frontend2/pullrequests/167/merge))
   (html (href . https://bitbucket.org/ptmtech/frontend2/pull-requests/167))
   (activity (href . https://api.bitbucket.org/2.0/repositories/ptmtech/frontend2/pullrequests/167/activity))
   (diff (href . https://api.bitbucket.org/2.0/repositories/ptmtech/frontend2/pullrequests/167/diff))
   (approve (href . https://api.bitbucket.org/2.0/repositories/ptmtech/frontend2/pullrequests/167/approve))
   (statuses (href . https://api.bitbucket.org/2.0/repositories/ptmtech/frontend2/pullrequests/167/statuses)))
  (title . WEB-726 #time 5h #comment Fix admin fontes multiple search by nomeClirea)
  (close_source_branch . t)
  (merge_commit)
  (destination
   (commit (hash . 11adb135a350) (links (self (href . https://api.bitbucket.org/2.0/repositories/ptmtech/frontend2/commit/11adb135a350))))
   (repository
    (links
     (self (href . https://api.bitbucket.org/2.0/repositories/ptmtech/frontend2))
     (html (href . https://bitbucket.org/ptmtech/frontend2))
     (avatar (href . https://bitbucket.org/ptmtech/frontend2/avatar/32/)))
    (type . repository)
    (name . frontend2)
    (full_name . ptmtech/frontend2)
    (uuid . {9a1a1aa2-67af-4f1e-9e27-f30b258bebee}))
   (branch (name . development)))
  (state . OPEN)
  (closed_by)
  (summary (raw . "") (markup . markdown) (html . ) (type . rendered))
  (source (commit (hash . 319ba1e39647) (links (self (href . https://api.bitbucket.org/2.0/repositories/ptmtech/frontend2/commit/319ba1e39647)))) (repository (links (self (href . https://api.bitbucket.org/2.0/repositories/ptmtech/frontend2)) (html (href . https://bitbucket.org/ptmtech/frontend2)) (avatar (href . https://bitbucket.org/ptmtech/frontend2/avatar/32/))) (type . repository) (name . frontend2) (full_name . ptmtech/frontend2) (uuid . {9a1a1aa2-67af-4f1e-9e27-f30b258bebee})) (branch (name . fix-admin-fontes-multiple-search)))
  (comment_count . 0)
  (author (username . dhiegohenrique) (display_name . Dhiego Henrique) (type . user) (uuid . {ef6b5cd7-7dfc-498d-a596-3316a179c36a}) (links (self (href . https://api.bitbucket.org/2.0/users/dhiegohenrique)) (html (href . https://bitbucket.org/dhiegohenrique/)) (avatar (href . https://bitbucket.org/account/dhiegohenrique/avatar/32/))))
  (created_on . 2018-03-08T19:03:37.688441+00:00)
  (reason . "")
  (updated_on . 2018-03-09T12:25:19.381327+00:00)
  (type . pullrequest)
  (id . 167) (task_count . 0))


 ((description . * WEB-725 #comment add request time condition to update data grid. #time 3h * WEB-725 #comment add header time when exist a token. #time 20m * WEB-725 #comment fix white space.)
  (links (decline (href . https://api.bitbucket.org/2.0/repositories/ptmtech/frontend2/pullrequests/166/decline)) (commits (href . https://api.bitbucket.org/2.0/repositories/ptmtech/frontend2/pullrequests/166/commits)) (self (href . https://api.bitbucket.org/2.0/repositories/ptmtech/frontend2/pullrequests/166)) (comments (href . https://api.bitbucket.org/2.0/repositories/ptmtech/frontend2/pullrequests/166/comments)) (merge (href . https://api.bitbucket.org/2.0/repositories/ptmtech/frontend2/pullrequests/166/merge)) (html (href . https://bitbucket.org/ptmtech/frontend2/pull-requests/166)) (activity (href . https://api.bitbucket.org/2.0/repositories/ptmtech/frontend2/pullrequests/166/activity)) (diff (href . https://api.bitbucket.org/2.0/repositories/ptmtech/frontend2/pullrequests/166/diff)) (approve (href . https://api.bitbucket.org/2.0/repositories/ptmtech/frontend2/pullrequests/166/approve)) (statuses (href . https://api.bitbucket.org/2.0/repositories/ptmtech/frontend2/pullrequests/166/statuses)))
  (title . Add time update data grid)
  (close_source_branch . t)
  (merge_commit)
  (destination (commit (hash . 11adb135a350) (links (self (href . https://api.bitbucket.org/2.0/repositories/ptmtech/frontend2/commit/11adb135a350)))) (repository (links (self (href . https://api.bitbucket.org/2.0/repositories/ptmtech/frontend2)) (html (href . https://bitbucket.org/ptmtech/frontend2)) (avatar (href . https://bitbucket.org/ptmtech/frontend2/avatar/32/))) (type . repository) (name . frontend2) (full_name . ptmtech/frontend2) (uuid . {9a1a1aa2-67af-4f1e-9e27-f30b258bebee})) (branch (name . development)))
  (state . OPEN)
  (closed_by)
  (summary (raw . * WEB-725 #comment add request time condition to update data grid. #time 3h* WEB-725 #comment add header time when exist a token. #time 20m * WEB-725 #comment fix white space.) (markup . markdown) (html . <ul></ul>) (type . rendered))
  (source (commit (hash . da76a4a27e6d) (links (self (href . https://api.bitbucket.org/2.0/repositories/ptmtech/frontend2/commit/da76a4a27e6d)))) (repository (links (self (href . https://api.bitbucket.org/2.0/repositories/ptmtech/frontend2)) (html (href . https://bitbucket.org/ptmtech/frontend2)) (avatar (href . https://bitbucket.org/ptmtech/frontend2/avatar/32/))) (type . repository) (name . frontend2) (full_name . ptmtech/frontend2) (uuid . {9a1a1aa2-67af-4f1e-9e27-f30b258bebee})) (branch (name . add-time-update-data-grid)))
  (comment_count . 0)
  (author (username . renanptm) (display_name . Renan Bet Rodrigues) (type . user) (uuid . {d88c1c7c-0cb0-497e-897c-2188f3984646}) (links (self (href . https://api.bitbucket.org/2.0/users/renanptm)) (html (href . https://bitbucket.org/renanptm/)) (avatar (href . https://bitbucket.org/account/renanptm/avatar/32/))))
  (created_on . 2018-03-08T13:21:21.603045+00:00)
  (reason . "") (updated_on . 2018-03-08T13:36:53.050759+00:00)
  (type . pullrequest)
  (id . 166)
  (task_count . 0))
 ]
