'((scm . "git")
  (website . "")
  (has_wiki . :json-false)
  (name . "testrepo")
  (links (watchers (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/testrepo/watchers"))
         (branches (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/testrepo/refs/branches"))
         (tags (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/testrepo/refs/tags"))
         (commits (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/testrepo/commits"))
         (clone . [((href . "https://mgmdevptm@bitbucket.org/mgmdevptm/testrepo.git")
                    (name . "https"))
                   ((href . "git@bitbucket.org:mgmdevptm/testrepo.git")
                    (name . "ssh"))])
         (self (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/testrepo"))
         (source (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/testrepo/src"))
         (html (href . "https://bitbucket.org/mgmdevptm/testrepo"))
         (avatar (href . "https://bitbucket.org/mgmdevptm/testrepo/avatar/32/"))
         (hooks (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/testrepo/hooks"))
         (forks (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/testrepo/forks"))
         (downloads (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/testrepo/downloads"))
         (pullrequests (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/testrepo/pullrequests")))
  (fork_policy . "no_public_forks")
  (uuid . "{10cebf11-d8d6-478f-a9c8-4f082158bc59}")
  (language . "")
  (created_on . "2018-03-20T04:12:09.081607+00:00")
  (mainbranch (type . "branch") (name . "master"))
  (full_name . "mgmdevptm/testrepo")
  (has_issues . :json-false)
  (owner (username . "mgmdevptm") (display_name . "Marcos Moritz") (type . "user") (uuid . "{3823713e-6372-4cf4-9e34-72a248f4d638}") (links (self (href . "https://api.bitbucket.org/2.0/users/mgmdevptm")) (html (href . "https://bitbucket.org/mgmdevptm/")) (avatar (href . "https://bitbucket.org/account/mgmdevptm/avatar/32/"))))
  (updated_on . "2018-03-31T15:47:07.422838+00:00")
  (size . 218170)
  (type . "repository")
  (slug . "testrepo")
  (is_private . t)
  (description . "test repo, only for testing bitbucket features"))
