(setq emacs-bitbucket-test--repositories
      '((pagelen . 30)
        (values
         .
         [((scm . "git")
           (website . "")
           (has_wiki . :json-false)
           (name . "DicomThumbnails")
           (links (watchers (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/dicomthumbnails/watchers"))
                  (branches (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/dicomthumbnails/refs/branches"))
                  (tags (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/dicomthumbnails/refs/tags"))
                  (commits (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/dicomthumbnails/commits"))
                  (clone . [((href . "https://mgmdevptm@bitbucket.org/mgmdevptm/dicomthumbnails.git")
                             (name . "https"))
                            ((href . "git@bitbucket.org:mgmdevptm/dicomthumbnails.git")
                             (name . "ssh"))])
                  (self (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/dicomthumbnails"))
                  (source (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/dicomthumbnails/src"))
                  (html (href . "https://bitbucket.org/mgmdevptm/dicomthumbnails"))
                  (avatar (href . "https://bitbucket.org/mgmdevptm/dicomthumbnails/avatar/32/"))
                  (hooks (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/dicomthumbnails/hooks"))
                  (forks (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/dicomthumbnails/forks"))
                  (downloads (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/dicomthumbnails/downloads"))
                  (pullrequests (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/dicomthumbnails/pullrequests")))
           (fork_policy . "no_public_forks")
           (uuid . "{67d0f68f-2d6b-41a3-aa07-d187ead05e9c}")
           (language . "")
           (created_on . "2016-02-04T20:00:46.092657+00:00")
           (mainbranch (type . "branch") (name . "master"))
           (full_name . "mgmdevptm/dicomthumbnails")
           (has_issues . :json-false)
           (owner (username . "mgmdevptm") (display_name . "Marcos Moritz") (type . "user") (uuid . "{3823713e-6372-4cf4-9e34-72a248f4d638}") (links (self (href . "https://api.bitbucket.org/2.0/users/mgmdevptm")) (html (href . "https://bitbucket.org/mgmdevptm/")) (avatar (href . "https://bitbucket.org/account/mgmdevptm/avatar/32/"))))
           (updated_on . "2016-08-25T22:45:55.979779+00:00")
           (size . 12691446)
           (type . "repository")
           (slug . "dicomthumbnails")
           (is_private . t)
           (description . ""))

          ((scm . "git") (website . "") (has_wiki . :json-false) (name . "DicomJoinLib") (links (watchers (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/dicomjoinlib/watchers")) (branches (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/dicomjoinlib/refs/branches")) (tags (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/dicomjoinlib/refs/tags")) (commits (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/dicomjoinlib/commits")) (clone . [((href . "https://mgmdevptm@bitbucket.org/mgmdevptm/dicomjoinlib.git") (name . "https")) ((href . "git@bitbucket.org:mgmdevptm/dicomjoinlib.git") (name . "ssh"))]) (self (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/dicomjoinlib")) (source (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/dicomjoinlib/src")) (html (href . "https://bitbucket.org/mgmdevptm/dicomjoinlib")) (avatar (href . "https://bitbucket.org/mgmdevptm/dicomjoinlib/avatar/32/")) (hooks (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/dicomjoinlib/hooks")) (forks (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/dicomjoinlib/forks")) (downloads (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/dicomjoinlib/downloads")) (pullrequests (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/dicomjoinlib/pullrequests"))) (fork_policy . "no_public_forks") (uuid . "{660bd9bf-0f9d-44c2-86f7-1036f2b373e9}") (language . "c#") (created_on . "2016-02-08T21:08:23.019279+00:00") (mainbranch (type . "branch") (name . "master")) (full_name . "mgmdevptm/dicomjoinlib") (has_issues . :json-false) (owner (username . "mgmdevptm") (display_name . "Marcos Moritz") (type . "user") (uuid . "{3823713e-6372-4cf4-9e34-72a248f4d638}") (links (self (href . "https://api.bitbucket.org/2.0/users/mgmdevptm")) (html (href . "https://bitbucket.org/mgmdevptm/")) (avatar (href . "https://bitbucket.org/account/mgmdevptm/avatar/32/")))) (updated_on . "2016-08-25T21:04:59.882914+00:00") (size . 13632646) (type . "repository") (slug . "dicomjoinlib") (is_private . t) (description . "Gets all dicom files from a client and puts together all files from the same patient"))

          ((scm . "git") (website . "") (has_wiki . :json-false) (name . "ptm_rbt_dicom_join") (links (watchers (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/ptm_rbt_dicom_join/watchers")) (branches (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/ptm_rbt_dicom_join/refs/branches")) (tags (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/ptm_rbt_dicom_join/refs/tags")) (commits (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/ptm_rbt_dicom_join/commits")) (clone . [((href . "https://mgmdevptm@bitbucket.org/mgmdevptm/ptm_rbt_dicom_join.git") (name . "https")) ((href . "git@bitbucket.org:mgmdevptm/ptm_rbt_dicom_join.git") (name . "ssh"))]) (self (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/ptm_rbt_dicom_join")) (source (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/ptm_rbt_dicom_join/src")) (html (href . "https://bitbucket.org/mgmdevptm/ptm_rbt_dicom_join")) (avatar (href . "https://bitbucket.org/mgmdevptm/ptm_rbt_dicom_join/avatar/32/")) (hooks (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/ptm_rbt_dicom_join/hooks")) (forks (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/ptm_rbt_dicom_join/forks")) (downloads (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/ptm_rbt_dicom_join/downloads")) (pullrequests (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/ptm_rbt_dicom_join/pullrequests"))) (fork_policy . "no_public_forks") (uuid . "{6df3af18-39ac-4791-910c-05908eb1ce36}") (language . "") (created_on . "2016-08-15T23:33:44.801716+00:00") (mainbranch (type . "branch") (name . "master")) (full_name . "mgmdevptm/ptm_rbt_dicom_join") (has_issues . :json-false) (owner (username . "mgmdevptm") (display_name . "Marcos Moritz") (type . "user") (uuid . "{3823713e-6372-4cf4-9e34-72a248f4d638}") (links (self (href . "https://api.bitbucket.org/2.0/users/mgmdevptm")) (html (href . "https://bitbucket.org/mgmdevptm/")) (avatar (href . "https://bitbucket.org/account/mgmdevptm/avatar/32/")))) (updated_on . "2016-08-24T00:22:24.201289+00:00") (size . 2146066) (type . "repository") (slug . "ptm_rbt_dicom_join") (is_private . t) (description . ""))

          ((scm . "git") (website . "") (has_wiki . :json-false) (name . "DicomParser") (links (watchers (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/dicomparser/watchers")) (branches (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/dicomparser/refs/branches")) (tags (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/dicomparser/refs/tags")) (commits (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/dicomparser/commits")) (clone . [((href . "https://mgmdevptm@bitbucket.org/mgmdevptm/dicomparser.git") (name . "https")) ((href . "git@bitbucket.org:mgmdevptm/dicomparser.git") (name . "ssh"))]) (self (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/dicomparser")) (source (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/dicomparser/src")) (html (href . "https://bitbucket.org/mgmdevptm/dicomparser")) (avatar (href . "https://bitbucket.org/mgmdevptm/dicomparser/avatar/32/")) (hooks (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/dicomparser/hooks")) (forks (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/dicomparser/forks")) (downloads (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/dicomparser/downloads")) (pullrequests (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/dicomparser/pullrequests"))) (fork_policy . "no_public_forks") (uuid . "{d7f87eab-7944-46c7-bf0c-bcbb8318ed21}") (language . "") (created_on . "2016-08-16T13:31:56.292141+00:00") (mainbranch (type . "branch") (name . "master")) (full_name . "mgmdevptm/dicomparser") (has_issues . :json-false) (owner (username . "mgmdevptm") (display_name . "Marcos Moritz") (type . "user") (uuid . "{3823713e-6372-4cf4-9e34-72a248f4d638}") (links (self (href . "https://api.bitbucket.org/2.0/users/mgmdevptm")) (html (href . "https://bitbucket.org/mgmdevptm/")) (avatar (href . "https://bitbucket.org/account/mgmdevptm/avatar/32/")))) (updated_on . "2016-08-16T14:09:45.610158+00:00") (size . 1091156) (type . "repository") (slug . "dicomparser") (is_private . t) (description . ""))

          ((scm . "git") (website . "") (has_wiki . :json-false) (name . "Gera Exame Pdf") (links (watchers (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/gera-exame-pdf/watchers")) (branches (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/gera-exame-pdf/refs/branches")) (tags (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/gera-exame-pdf/refs/tags")) (commits (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/gera-exame-pdf/commits")) (clone . [((href . "https://mgmdevptm@bitbucket.org/mgmdevptm/gera-exame-pdf.git") (name . "https")) ((href . "git@bitbucket.org:mgmdevptm/gera-exame-pdf.git") (name . "ssh"))]) (self (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/gera-exame-pdf")) (source (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/gera-exame-pdf/src")) (html (href . "https://bitbucket.org/mgmdevptm/gera-exame-pdf")) (avatar (href . "https://bitbucket.org/mgmdevptm/gera-exame-pdf/avatar/32/")) (hooks (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/gera-exame-pdf/hooks")) (forks (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/gera-exame-pdf/forks")) (downloads (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/gera-exame-pdf/downloads")) (pullrequests (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/gera-exame-pdf/pullrequests"))) (fork_policy . "no_public_forks") (uuid . "{6224b61e-f393-439c-a8d4-a5f416a68d33}") (language . "c#") (created_on . "2016-10-26T16:14:03.401879+00:00") (mainbranch (type . "branch") (name . "master")) (full_name . "mgmdevptm/gera-exame-pdf") (has_issues . :json-false) (owner (username . "mgmdevptm") (display_name . "Marcos Moritz") (type . "user") (uuid . "{3823713e-6372-4cf4-9e34-72a248f4d638}") (links (self (href . "https://api.bitbucket.org/2.0/users/mgmdevptm")) (html (href . "https://bitbucket.org/mgmdevptm/")) (avatar (href . "https://bitbucket.org/account/mgmdevptm/avatar/32/")))) (updated_on . "2016-10-26T17:52:05.818204+00:00") (size . 1712388) (type . "repository") (slug . "gera-exame-pdf") (is_private . t) (description . ""))

          ((scm . "git") (website . "") (has_wiki . :json-false) (name . "poc-new-laudar") (links (watchers (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/poc-new-laudar/watchers")) (branches (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/poc-new-laudar/refs/branches")) (tags (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/poc-new-laudar/refs/tags")) (commits (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/poc-new-laudar/commits")) (clone . [((href . "https://mgmdevptm@bitbucket.org/mgmdevptm/poc-new-laudar.git") (name . "https")) ((href . "git@bitbucket.org:mgmdevptm/poc-new-laudar.git") (name . "ssh"))]) (self (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/poc-new-laudar")) (source (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/poc-new-laudar/src")) (html (href . "https://bitbucket.org/mgmdevptm/poc-new-laudar")) (avatar (href . "https://bitbucket.org/mgmdevptm/poc-new-laudar/avatar/32/")) (hooks (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/poc-new-laudar/hooks")) (forks (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/poc-new-laudar/forks")) (downloads (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/poc-new-laudar/downloads")) (pullrequests (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/poc-new-laudar/pullrequests"))) (fork_policy . "no_public_forks") (uuid . "{707cafa3-ff6f-48a1-bf9f-0492942b07b3}") (language . "javascript") (created_on . "2017-04-18T04:04:56.191341+00:00") (mainbranch (type . "branch") (name . "master")) (full_name . "mgmdevptm/poc-new-laudar") (has_issues . :json-false) (owner (username . "mgmdevptm") (display_name . "Marcos Moritz") (type . "user") (uuid . "{3823713e-6372-4cf4-9e34-72a248f4d638}") (links (self (href . "https://api.bitbucket.org/2.0/users/mgmdevptm")) (html (href . "https://bitbucket.org/mgmdevptm/")) (avatar (href . "https://bitbucket.org/account/mgmdevptm/avatar/32/")))) (updated_on . "2017-04-18T04:06:23.906522+00:00") (size . 76183) (type . "repository") (slug . "poc-new-laudar") (is_private . t) (description . "UI for laudar with multiple files and download option"))

          ((scm . "git") (website . "") (has_wiki . :json-false) (name . "POC Drive") (links (watchers (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/poc-drive/watchers")) (branches (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/poc-drive/refs/branches")) (tags (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/poc-drive/refs/tags")) (commits (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/poc-drive/commits")) (clone . [((href . "https://mgmdevptm@bitbucket.org/mgmdevptm/poc-drive.git") (name . "https")) ((href . "git@bitbucket.org:mgmdevptm/poc-drive.git") (name . "ssh"))]) (self (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/poc-drive")) (source (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/poc-drive/src")) (html (href . "https://bitbucket.org/mgmdevptm/poc-drive")) (avatar (href . "https://bitbucket.org/mgmdevptm/poc-drive/avatar/32/")) (hooks (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/poc-drive/hooks")) (forks (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/poc-drive/forks")) (downloads (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/poc-drive/downloads")) (pullrequests (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/poc-drive/pullrequests"))) (fork_policy . "no_public_forks") (uuid . "{c7c7104e-9064-403f-8783-ac5577433fd6}") (language . "") (created_on . "2017-07-03T14:27:06.260196+00:00") (mainbranch (type . "branch") (name . "master")) (full_name . "mgmdevptm/poc-drive") (has_issues . :json-false) (owner (username . "mgmdevptm") (display_name . "Marcos Moritz") (type . "user") (uuid . "{3823713e-6372-4cf4-9e34-72a248f4d638}") (links (self (href . "https://api.bitbucket.org/2.0/users/mgmdevptm")) (html (href . "https://bitbucket.org/mgmdevptm/")) (avatar (href . "https://bitbucket.org/account/mgmdevptm/avatar/32/")))) (updated_on . "2017-07-03T14:28:10.063491+00:00") (size . 184520) (type . "repository") (slug . "poc-drive") (is_private . t) (description . "This is a sipmle proof of concept, a tiny façade to google drive api.
It does not claim to be complete or correct. It access the google drive service account and allow simple actions to list, upload and delete files."))

          ((scm . "git") (website . "") (has_wiki . :json-false) (name . "Multitasks") (links (watchers (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/multitasks/watchers")) (branches (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/multitasks/refs/branches")) (tags (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/multitasks/refs/tags")) (commits (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/multitasks/commits")) (clone . [((href . "https://mgmdevptm@bitbucket.org/mgmdevptm/multitasks.git") (name . "https")) ((href . "git@bitbucket.org:mgmdevptm/multitasks.git") (name . "ssh"))]) (self (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/multitasks")) (source (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/multitasks/src")) (html (href . "https://bitbucket.org/mgmdevptm/multitasks")) (avatar (href . "https://bitbucket.org/mgmdevptm/multitasks/avatar/32/")) (hooks (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/multitasks/hooks")) (forks (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/multitasks/forks")) (downloads (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/multitasks/downloads")) (pullrequests (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/multitasks/pullrequests"))) (fork_policy . "no_public_forks") (uuid . "{6e945fbc-2f61-425b-bdee-0cb3194fc087}") (language . "") (created_on . "2017-07-04T20:46:47.533527+00:00") (mainbranch (type . "branch") (name . "master")) (full_name . "mgmdevptm/multitasks") (has_issues . :json-false) (owner (username . "mgmdevptm") (display_name . "Marcos Moritz") (type . "user") (uuid . "{3823713e-6372-4cf4-9e34-72a248f4d638}") (links (self (href . "https://api.bitbucket.org/2.0/users/mgmdevptm")) (html (href . "https://bitbucket.org/mgmdevptm/")) (avatar (href . "https://bitbucket.org/account/mgmdevptm/avatar/32/")))) (updated_on . "2017-07-04T20:48:32.442011+00:00") (size . 155855) (type . "repository") (slug . "multitasks") (is_private . t) (description . ""))

          ((scm . "git") (website . "") (has_wiki . :json-false) (name . "CloudStorage") (links (watchers (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/cloudstorage/watchers")) (branches (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/cloudstorage/refs/branches")) (tags (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/cloudstorage/refs/tags")) (commits (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/cloudstorage/commits")) (clone . [((href . "https://mgmdevptm@bitbucket.org/mgmdevptm/cloudstorage.git") (name . "https")) ((href . "git@bitbucket.org:mgmdevptm/cloudstorage.git") (name . "ssh"))]) (self (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/cloudstorage")) (source (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/cloudstorage/src")) (html (href . "https://bitbucket.org/mgmdevptm/cloudstorage")) (avatar (href . "https://bitbucket.org/mgmdevptm/cloudstorage/avatar/32/")) (hooks (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/cloudstorage/hooks")) (forks (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/cloudstorage/forks")) (downloads (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/cloudstorage/downloads")) (pullrequests (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/cloudstorage/pullrequests"))) (fork_policy . "no_public_forks") (uuid . "{01e0593d-740c-4922-9549-d00497c74a27}") (language . "c#") (created_on . "2017-10-04T15:01:38.590061+00:00") (mainbranch (type . "branch") (name . "master")) (full_name . "mgmdevptm/cloudstorage") (has_issues . :json-false) (owner (username . "mgmdevptm") (display_name . "Marcos Moritz") (type . "user") (uuid . "{3823713e-6372-4cf4-9e34-72a248f4d638}") (links (self (href . "https://api.bitbucket.org/2.0/users/mgmdevptm")) (html (href . "https://bitbucket.org/mgmdevptm/")) (avatar (href . "https://bitbucket.org/account/mgmdevptm/avatar/32/")))) (updated_on . "2017-12-11T13:55:34.253457+00:00") (size . 339133) (type . "repository") (slug . "cloudstorage") (is_private . t) (description . "[Obsolete]
Client for multiple storage vendors
The working version is CloudStorageN46"))

          ((scm . "git") (website . "") (has_wiki . :json-false) (name . "docs") (links (watchers (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/docs/watchers")) (branches (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/docs/refs/branches")) (tags (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/docs/refs/tags")) (commits (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/docs/commits")) (clone . [((href . "https://mgmdevptm@bitbucket.org/mgmdevptm/docs.git") (name . "https")) ((href . "git@bitbucket.org:mgmdevptm/docs.git") (name . "ssh"))]) (self (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/docs")) (source (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/docs/src")) (html (href . "https://bitbucket.org/mgmdevptm/docs")) (avatar (href . "https://bitbucket.org/mgmdevptm/docs/avatar/32/")) (hooks (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/docs/hooks")) (forks (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/docs/forks")) (downloads (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/docs/downloads")) (pullrequests (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/docs/pullrequests"))) (fork_policy . "no_public_forks") (uuid . "{5df076e7-f42e-448a-aea3-7ed30bd089eb}") (language . "") (created_on . "2017-10-18T16:44:34.002179+00:00") (mainbranch (type . "branch") (name . "master")) (full_name . "mgmdevptm/docs") (has_issues . :json-false) (owner (username . "mgmdevptm") (display_name . "Marcos Moritz") (type . "user") (uuid . "{3823713e-6372-4cf4-9e34-72a248f4d638}") (links (self (href . "https://api.bitbucket.org/2.0/users/mgmdevptm")) (html (href . "https://bitbucket.org/mgmdevptm/")) (avatar (href . "https://bitbucket.org/account/mgmdevptm/avatar/32/")))) (updated_on . "2017-10-19T20:01:56.758880+00:00") (size . 466811) (type . "repository") (slug . "docs") (is_private . t) (description . "Simple and informal docs repository"))

          ((scm . "git") (website . "") (has_wiki . :json-false) (name . "sprints") (links (watchers (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/sprints/watchers")) (branches (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/sprints/refs/branches")) (tags (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/sprints/refs/tags")) (commits (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/sprints/commits")) (clone . [((href . "https://mgmdevptm@bitbucket.org/mgmdevptm/sprints.git") (name . "https")) ((href . "git@bitbucket.org:mgmdevptm/sprints.git") (name . "ssh"))]) (self (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/sprints")) (source (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/sprints/src")) (html (href . "https://bitbucket.org/mgmdevptm/sprints")) (avatar (href . "https://bitbucket.org/mgmdevptm/sprints/avatar/32/")) (hooks (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/sprints/hooks")) (forks (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/sprints/forks")) (downloads (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/sprints/downloads")) (pullrequests (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/sprints/pullrequests"))) (fork_policy . "no_public_forks") (uuid . "{2ca783b3-5c08-42f0-b4ed-148535ecffbe}") (language . "") (created_on . "2017-10-18T16:53:54.911099+00:00") (mainbranch (type . "branch") (name . "master")) (full_name . "mgmdevptm/sprints") (has_issues . :json-false) (owner (username . "mgmdevptm") (display_name . "Marcos Moritz") (type . "user") (uuid . "{3823713e-6372-4cf4-9e34-72a248f4d638}") (links (self (href . "https://api.bitbucket.org/2.0/users/mgmdevptm")) (html (href . "https://bitbucket.org/mgmdevptm/")) (avatar (href . "https://bitbucket.org/account/mgmdevptm/avatar/32/")))) (updated_on . "2018-03-29T01:54:34.259042+00:00") (size . 7097643) (type . "repository") (slug . "sprints") (is_private . t) (description . "Org files to personal management of sprints"))

          ((scm . "git") (website . "") (has_wiki . :json-false) (name . "testrepo") (links (watchers (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/testrepo/watchers")) (branches (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/testrepo/refs/branches")) (tags (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/testrepo/refs/tags")) (commits (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/testrepo/commits")) (clone . [((href . "https://mgmdevptm@bitbucket.org/mgmdevptm/testrepo.git") (name . "https")) ((href . "git@bitbucket.org:mgmdevptm/testrepo.git") (name . "ssh"))]) (self (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/testrepo")) (source (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/testrepo/src")) (html (href . "https://bitbucket.org/mgmdevptm/testrepo")) (avatar (href . "https://bitbucket.org/mgmdevptm/testrepo/avatar/32/")) (hooks (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/testrepo/hooks")) (forks (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/testrepo/forks")) (downloads (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/testrepo/downloads")) (pullrequests (href . "https://api.bitbucket.org/2.0/repositories/mgmdevptm/testrepo/pullrequests"))) (fork_policy . "no_public_forks") (uuid . "{10cebf11-d8d6-478f-a9c8-4f082158bc59}") (language . "") (created_on . "2018-03-20T04:12:09.081607+00:00") (mainbranch (type . "branch") (name . "master")) (full_name . "mgmdevptm/testrepo") (has_issues . :json-false) (owner (username . "mgmdevptm") (display_name . "Marcos Moritz") (type . "user") (uuid . "{3823713e-6372-4cf4-9e34-72a248f4d638}") (links (self (href . "https://api.bitbucket.org/2.0/users/mgmdevptm")) (html (href . "https://bitbucket.org/mgmdevptm/")) (avatar (href . "https://bitbucket.org/account/mgmdevptm/avatar/32/")))) (updated_on . "2018-03-31T15:47:07.422838+00:00") (size . 218170) (type . "repository") (slug . "testrepo") (is_private . t) (description . "test repo, only for testing bitbucket features"))])
        (page . 1)
        (size . 12)))
